/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/desk.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/desk.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.294, 1.36, -6.337]} scale={0.302}>
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1462626064|Dupli|7'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1658787459|Dupli|18'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1698824667|Dupli|12'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1746518091|Dupli|8'].geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1783798096|Dupli|3'].geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1896072715|Dupli|19'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2060347243|Dupli|9'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2063576334|Dupli|11'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2070617275|Dupli|13'].geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2128326706|Dupli|16'].geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group451364077|Dupli|20'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group575146565|Dupli|6'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group625259463|Dupli|4'].geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group710626981|Dupli|14'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group786212531|Dupli|21'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10'].geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group974294459|Dupli|17'].geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes.mesh150401702001.geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes.mesh150401702001_1.geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes.mesh329542522001.geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes.mesh329542522001_1.geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes.mesh576947092001.geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes.mesh576947092001_1.geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes.mesh860618825001.geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes.mesh860618825001_1.geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes.mesh860618825001_2.geometry} material={materials['mat21.012']} />
        <mesh geometry={nodes.mesh1691283673001.geometry} material={materials['mat22.010']} />
        <mesh geometry={nodes.mesh1691283673001_1.geometry} material={materials['mat23.015']} />
        <mesh geometry={nodes.mesh1691283673001_2.geometry} material={materials['mat21.012']} />
      </group>
      <group position={[-0.284, 1.216, -6.705]} rotation={[3.136, 0.04, 3.14]} scale={0.205}>
        <mesh geometry={nodes['Keyboard|group1030983910|Dupli|22'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1075691498|Dupli|58'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1149852049|Dupli|53'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1152190519|Dupli|19'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1180881246|Dupli|50'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1238060299|Dupli|28'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1238428394|Dupli|61'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1272091893|Dupli|35'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1316349499|Dupli|39'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1323238240|Dupli|32'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group145618305|Dupli|23'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1486350934|Dupli|63'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group150579309|Dupli|11'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1529968652|Dupli|6'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1571332333|Dupli|33'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1581414308|Dupli|8'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1589752359|Dupli|26'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1629393722|Dupli|64'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1629609685|Dupli|21'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1675960081|Dupli|12'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1740918352|Dupli|46'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1753917514|Dupli|5'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1754683637|Dupli|40'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1764140354|Dupli|60'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1870575723|Dupli|65'].geometry} material={materials['mat16.006']} />
        <mesh geometry={nodes['Keyboard|group1899843208|Dupli|36'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1956214489|Dupli|14'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group196400395|Dupli|15'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group1976194690|Dupli|18'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group205302596|Dupli|31'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group2074153597|Dupli|20'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group2085389804|Dupli|57'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group2091112366|Dupli|59'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group2106755496|Dupli|4'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group2146178072|Dupli|38'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group252681800|Dupli|7'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group268332703|Dupli|44'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group287159489|Dupli|13'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group295085766|Dupli|9'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group311988427|Dupli|1'].geometry} material={materials['mat22.011']} />
        <mesh geometry={nodes['Keyboard|group34220672|Dupli|34'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group384612072|Dupli|10'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group418912012|Dupli|30'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group42243725|Dupli|37'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group425587018|Dupli|'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group449779970|Dupli|3'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group45382983|Dupli|52'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group475225180|Dupli|41'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group573547017|Dupli|49'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group588539140|Dupli|47'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group601803475|Dupli|25'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group616518658|Dupli|56'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group687259746|Dupli|51'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group706802639|Dupli|17'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group729811280|Dupli|48'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group77921105|Dupli|42'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group790925258|Dupli|54'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group801095923|Dupli|29'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group806343109|Dupli|27'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group826580911|Dupli|24'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group873458270|Dupli|55'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group873558583|Dupli|62'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group877249531|Dupli|66'].geometry} material={materials['mat9.002']} />
        <mesh geometry={nodes['Keyboard|group954813675|Dupli|16'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group96314515|Dupli|2'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group96968687|Dupli|43'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard|group993315105|Dupli|45'].geometry} material={materials['mat21.013']} />
      </group>
      <group position={[-0.805, 0.937, -6.105]} scale={1.296}>
        <mesh geometry={nodes['Mug_With_Office_Tool|Mug_with_office_tools|Dupli|'].geometry} material={materials['Material.015']} scale={100} />
      </group>
      <group position={[-1.161, 0.942, -6.524]} scale={0.186}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Soda001_1.geometry} material={materials['White.005']} />
          <mesh geometry={nodes.Soda001_2.geometry} material={materials['Red.002']} />
        </group>
      </group>
      <group position={[0.255, 0.942, -6.492]} rotation={[Math.PI, -0.285, Math.PI]} scale={0.031}>
        <mesh geometry={nodes.Notebook_Cube041_1001.geometry} material={materials['FFEB3B.002']} />
        <mesh geometry={nodes.Notebook_Cube041_1001_1.geometry} material={materials['795548.003']} />
        <mesh geometry={nodes.Notebook_Cube041_1001_2.geometry} material={materials['F44336.006']} />
      </group>
      <mesh geometry={nodes.Mousepad001.geometry} material={materials.Mousepad} position={[-1.132, 0.944, -6.86]} rotation={[0, 1.571, 0]} scale={[0.172, 0.002, 0.21]} />
      <group position={[0.338, 1.01, -6.188]} rotation={[-Math.PI / 2, 0, -2.997]} scale={7.816}>
        <mesh geometry={nodes.Office_Phone001_1.geometry} material={materials['Light grey']} />
        <mesh geometry={nodes.Office_Phone001_2.geometry} material={materials['Grey Plastic']} />
        <mesh geometry={nodes.Office_Phone001_3.geometry} material={materials.Screen} />
        <mesh geometry={nodes.Office_Phone001_4.geometry} material={materials['Dark Grey Plastic']} />
      </group>
      <group position={[-1.101, 0.942, -6.167]} rotation={[-Math.PI, 0.388, -Math.PI]} scale={0.012}>
        <mesh geometry={nodes['Calendar-8GqQAqxi3qk_1'].geometry} material={materials.Calendar_Aquamarine} />
        <mesh geometry={nodes['Calendar-8GqQAqxi3qk_2'].geometry} material={materials.Calendar_Ivory} />
        <mesh geometry={nodes['Calendar-8GqQAqxi3qk_3'].geometry} material={materials.Calendar_Texture} />
        <mesh geometry={nodes['Calendar-8GqQAqxi3qk_4'].geometry} material={materials.FrontColor} />
      </group>
      <group position={[-0.456, 0, -6.33]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube006_Cube007_BlackCoatSteel.geometry} material={materials.BlackCoatSteel} />
        <mesh geometry={nodes.Cube006_Cube007_BlackCoatSteel_1.geometry} material={materials.GrayPlastic} />
        <mesh geometry={nodes.Cube006_Cube007_BlackCoatSteel_2.geometry} material={materials.WhiteSteelScrew} />
        <mesh geometry={nodes.Cube006_Cube007_BlackCoatSteel_3.geometry} material={materials.BlackPlastic} />
        <mesh geometry={nodes.Cube006_Cube007_BlackCoatSteel_4.geometry} material={materials.BlackWood} />
      </group>
      <mesh geometry={nodes.Mouse001.geometry} material={materials['Material.001']} position={[-1.139, 0.942, -6.856]} rotation={[Math.PI, -0.452, Math.PI]} scale={100} />
    </group>
  )
}

useGLTF.preload('/desk.glb')
