/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/cypressTree.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CypressTree(props) {
  const { nodes, materials } = useGLTF('/src/assets/cypressTree.glb')
  return (
    <group {...props} dispose={null} position={[5,5,0]} scale={[40,40,40]}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat9} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat19} />
    </group>
  )
}

useGLTF.preload('/src/assets/cypressTree.glb')
