/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Stairs.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Stairs(props) {
  const { nodes, materials } = useGLTF('public/Stairs.glb')
  return (
    <group {...props} dispose={null} position={[86,-3,60]} scale={0.6}>
      <mesh geometry={nodes.Stair.geometry} material={materials['07___Default']} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder018.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder019.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder020.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder026.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder027.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder028.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder029.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder030.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder031.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Cylinder032.geometry} material={materials['07___Default-2']} />
      <mesh geometry={nodes.Box001.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Box002.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Box004.geometry} material={materials['01___Default']} />
    </group>
  )
}

useGLTF.preload('public/Stairs.glb')
