/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/television.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
export default function Television() {
  const map=useLoader(TextureLoader,'public/planefolio.png')
  const { nodes, materials } = useGLTF('public/television.glb')
  return (
    <group dispose={null} scale={[10,10,10]} position={[98,25,0]} rotation-y={3*Math.PI/2}>
      <mesh geometry={nodes.group1257628551.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1840578182.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group596176051.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group397977436.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1562963861.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1468930754.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1923268096.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group207519990.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group108534205.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group83437352.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group2052255221.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1457147635.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1601593260.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1454904968.geometry} material={new THREE.MeshStandardMaterial({map:map,})} />
      <mesh geometry={nodes.mesh1454904968_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1454904968_2.geometry} material={materials.mat16} />
    </group>
  )
}

useGLTF.preload('public/television.glb')
